<?php

use Lunar\Base\StandardMediaDefinitions;
use Modules\Assets\Definitions\FashionMediaDefinitions;

/**
 * Module-local overrides for Lunar's `lunar.media` config.
 *
 * Kept here (not in config/lunar/media.php) so `php artisan vendor:publish
 * --tag=lunar --force` can never wipe them — AssetsServiceProvider re-applies
 * these over the published Lunar defaults at boot. Only list the keys we change.
 */
return [
    // On-demand conversion behaviour (read by MediaUrl / ConversionGenerator).
    'on_demand' => [
        // When false (default), a page render does NO image IO at all: it emits
        // the exact conversion URL and a missing file is generated by the
        // browser's own image request via the media.conversion fallback route
        // (one size per request, in parallel; uploads pre-warm all sizes on the
        // `media` queue). When true, the first request for a missing conversion
        // generates it inline during the render (serial — a page with many
        // missing sizes renders slowly).
        'sync' => (bool) env('MEDIA_ON_DEMAND_SYNC', false),
    ],

    'definitions' => [
        // Media Library assets get the same responsive + WebP conversions as
        // storefront imagery so picked files are ready for the front end.
        'asset' => FashionMediaDefinitions::class,
        // Storefront-facing models get responsive + WebP conversions.
        'collection' => FashionMediaDefinitions::class,
        'product' => FashionMediaDefinitions::class,
        // The rest stay on Lunar's StandardMediaDefinitions. Listed explicitly
        // for documentation only — both already resolve to StandardMediaDefinitions
        // via HasMedia::getDefinitionClass()'s fallback, so these two lines change
        // nothing.
        //
        // WARNING: 'product-option' is a DEAD key — the lookup snake_cases the
        // model basename (see the note below), so only 'product_option' would
        // ever match. If you need to give ProductOption real conversions, add it
        // under the snake_case key; editing this kebab-case line has no effect.
        'brand' => StandardMediaDefinitions::class,
        'product-option' => StandardMediaDefinitions::class,
        // Option values carry the variant `swatch` collection (colour/pattern
        // chips), so they need FashionMediaDefinitions' swatch conversions.
        // NB: lookups snake_case the model basename, so this key — not the
        // kebab-case 'product-option-value' — is the one that matches.
        'product_option_value' => FashionMediaDefinitions::class,
    ],
];
